language: go
sudo: false
go:
  - 1.4.2
  - 1.5.1
  - tip
env:
  - GOARCH=amd64
  - GOARCH=386
install:
  - export PATH="$HOME/gopath/bin:$PATH"
  - go get github.com/tools/godep
  - godep restore ./...
script:
  - go test -x ./tsuru
