language: go
go:
  - 1.1.2
  - 1.2
  - 1.3
  - tip
env:
  - GOARCH=amd64
  - GOARCH=386
install:
  - go get github.com/tools/godep
  - go get -d ./...
  - godep restore ./...
script:
  - go test ./...
