language: go
sudo: required
install: true
os:
  - linux
  - osx
go:
  - 1.8.x
  - master
env:
  global:
    - GO_FOR_RELEASE=1.8
  matrix:
    - GOARCH=amd64
    - GOARCH=386
before_install:
  - '[[ $TRAVIS_OS_NAME == "linux" ]] && sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0 || true'
  - '[[ $TRAVIS_OS_NAME == "linux" ]] && sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=0 || true'
script:
  - ./go.test.bash
  - '[[ $TRAVIS_GO_VERSION == "1.8" ]] && ./check-fmt.sh || true'
services:
  - redis
  - mongodb
matrix:
  allow_failures:
    - go: master
notifications:
  slack:
    secure: dDuxAhF7DgwmCvb3V7nu01+RUhvxhOCiBfGVC6596nx93ThjbTgPcMdkAdO7Xk4zFQcH3AiF3+ionMTSk+4oxRIBI0i4p71AkQoFUARWCfmLYWlztZ3Wii4/3bT36bzn5NPqGbNXhx2sWRzOO2W01jQLyFFdZlVKVTBqwBqHqG4=
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - [[ "$TRAVIS_TAG" =~ ^[0-9\.]+$ ]] && cat goreleaser-brew.yml >> goreleaser.yml
  - test -n "$TRAVIS_TAG" && curl -sL https://raw.githubusercontent.com/tsuru/push-to-packagecloud/master/push.sh | PACKAGE_NAME=tsuru bash
