language: go
sudo: required
install: true
os:
  - linux
  - osx
go:
  - 1.12.x
env:
  global:
    - GO_FOR_RELEASE=1.12
    - GORELEASER_CONFIG=goreleaser-rc.yml
    - GOPROXY=https://proxy.golang.org
    - GO111MODULE=on
  matrix:
    - GOARCH=amd64 JOB=test
    - GOARCH=386 JOB=test
    - GOARCH=amd64 JOB=gometalinter
before_install:
  - '[[ $TRAVIS_OS_NAME == "linux" ]] && sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0 || true'
  - '[[ $TRAVIS_OS_NAME == "linux" ]] && sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=0 || true'
script:
  - 'if [ "${JOB}" = "test" ]; then ./go.test.bash; fi'
  - 'if [ "${JOB}" = "gometalinter" ]; then make metalint; fi'
services:
  - redis
  - mongodb
jobs:
  fast_finish: true
  allow_failures:
    - go: master
  exclude:
    - os: osx
      env: GOARCH=amd64 JOB=gometalinter
    - os: osx
      env: GOARCH=386 JOB=test
  include:
    - os: linux
      go: master
      env: GOARCH=amd64 JOB=test
    - stage: deploy
      script:
        - 'if [[ "$TRAVIS_TAG" =~ ^[0-9\.]+$ ]]; then export GORELEASER_CONFIG=goreleaser-stable.yml; fi'
        - 'if [ -n "$TRAVIS_TAG" ]; then curl -sL https://raw.githubusercontent.com/tsuru/push-to-packagecloud/master/push.sh | PACKAGE_NAME=tsuru bash; fi'
      env: JOB=packagecloud
notifications:
  slack:
    secure: dDuxAhF7DgwmCvb3V7nu01+RUhvxhOCiBfGVC6596nx93ThjbTgPcMdkAdO7Xk4zFQcH3AiF3+ionMTSk+4oxRIBI0i4p71AkQoFUARWCfmLYWlztZ3Wii4/3bT36bzn5NPqGbNXhx2sWRzOO2W01jQLyFFdZlVKVTBqwBqHqG4=
after_success:
  - bash <(curl -s https://codecov.io/bash)
